// sampleTransactions is a set of random transactions
// One of these at random gets assigned to new users
const sampleTransactions = [
  {
    creditLimit: 500,
    events: [
      {
        eventType: "TXN_AUTHED",
        eventTime: 1,
        txnId: "t1",
        amount: 12,
        name: "Bart",
        type: "Travel",
        time: 1695280229000,
      },
      {
        eventType: "TXN_SETTLED",
        eventTime: 2,
        txnId: "t1",
        amount: 12,
        name: "Bart",
        type: "Travel",
        time: 1695366629000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 3,
        txnId: "t2",
        amount: 45,
        name: "Adela's Cakes",
        type: "Food",
        time: 1695539429000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 4,
        txnId: "t3",
        amount: 110,
        name: "Stanford Bookstore",
        type: "Shopping",
        time: 1695712229000,
      },
    ],
  },
  {
    creditLimit: 1500,
    events: [
      {
        eventType: "TXN_AUTHED",
        eventTime: 1,
        txnId: "t1",
        amount: 60,
        name: "Spirit Halloween",
        type: "Shopping",
        time: 1698390629000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 2,
        txnId: "t2",
        amount: 40,
        name: "MTL's Candy Shop",
        type: "Shopping",
        time: 1698563429000,
      },
    ],
  },
  {
    creditLimit: 1000,
    events: [
      {
        eventType: "TXN_AUTHED",
        eventTime: 1,
        txnId: "t1",
        amount: 500,
        name: "Ashish's Cookies",
        type: "Food",
        time: 1701735891000,
      },
      {
        eventType: "TXN_SETTLED",
        eventTime: 2,
        txnId: "t1",
        amount: 500,
        name: "Ashish's Cookies",
        type: "Food",
        time: 1701822291000,
      },
      {
        eventType: "PAYMENT_INITIATED",
        eventTime: 3,
        txnId: "p1",
        amount: -300,
        name: "Payment",
        type: "*******0123",
        time: 1701854691000,
      },
      {
        eventType: "PAYMENT_POSTED",
        eventTime: 4,
        txnId: "p1",
        name: "Payment",
        type: "Account *******0123",
        time: 1701941091000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 5,
        txnId: "t2",
        amount: 100,
        name: "Southwest Airlines",
        type: "Travel",
        time: 1702113891000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 6,
        txnId: "t3",
        amount: 100,
        name: "Shell",
        type: "Gas",
        time: 1702121091000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 7,
        txnId: "t4",
        amount: 100,
        name: "Target",
        type: "Shopping",
        time: 1702293891000,
      },
    ],
  },
  {
    creditLimit: 25000,
    events: [
      {
        eventType: "TXN_AUTHED",
        eventTime: 1,
        txnId: "t1",
        amount: 5000,
        name: "Rolex",
        type: "Shopping",
        time: 1699773029000,
      },
      {
        eventType: "TXN_SETTLED",
        eventTime: 2,
        txnId: "t1",
        amount: 5000,
        name: "Rolex",
        type: "Shopping",
        time: 1699773029000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 3,
        txnId: "t2",
        amount: 500,
        name: "Taylor Swift Tickets",
        type: "Entertainment",
        time: 1699945829000,
      },
      {
        eventType: "PAYMENT_INITIATED",
        eventTime: 4,
        txnId: "p1",
        amount: -3000,
        name: "Payment",
        type: "*******0123",
        time: 1700032229000,
      },
      {
        eventType: "PAYMENT_POSTED",
        eventTime: 5,
        txnId: "p1",
        name: "Payment",
        type: "Account *******0123",
        time: 1700205029000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 6,
        txnId: "t3",
        amount: 1200,
        name: "French Laundry",
        type: "Food",
        time: 1700637029000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 7,
        txnId: "t4",
        amount: 600,
        name: "William Sonoma",
        type: "Shopping",
        time: 1702121091000,
      },
      {
        eventType: "TXN_SETTLED",
        eventTime: 8,
        txnId: "t3",
        amount: 1200,
        name: "French Laundry",
        type: "Food",
        time: 1700809829000,
      },
    ],
  },
  {
    creditLimit: 75,
    events: [
      {
        eventType: "TXN_AUTHED",
        eventTime: 1,
        txnId: "t1",
        amount: 23,
        name: "Walmart",
        type: "Shopping",
        time: 1701414629000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 2,
        txnId: "t2",
        amount: 30,
        name: "Taco Bell",
        type: "Food",
        time: 1701501029000,
      },
      {
        eventType: "TXN_SETTLED",
        eventTime: 3,
        txnId: "t2",
        amount: 30,
        name: "Taco Bell",
        type: "Food",
        time: 1701673829000,
      },
      {
        eventType: "TXN_SETTLED",
        eventTime: 4,
        txnId: "t1",
        amount: 23,
        name: "Walmart",
        type: "Shopping",
        time: 1701760229000,
      },
      {
        eventType: "PAYMENT_INITIATED",
        eventTime: 5,
        txnId: "p1",
        amount: -50,
        name: "Payment",
        type: "*******0123",
        time: 1701846629000,
      },
      {
        eventType: "PAYMENT_POSTED",
        eventTime: 6,
        txnId: "p1",
        name: "Payment",
        type: "Account *******0123",
        time: 1702105829000,
      },
    ],
  },
  {
    creditLimit: 2000,
    events: [
      {
        eventType: "TXN_AUTHED",
        eventTime: 1,
        txnId: "t1",
        amount: 35,
        name: "Safeway",
        type: "Groceries",
        time: 1695280229000,
      },
      {
        eventType: "TXN_SETTLED",
        eventTime: 2,
        txnId: "t1",
        amount: 35,
        name: "Safeway",
        type: "Groceries",
        time: 1695366629000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 3,
        txnId: "t2",
        amount: 95,
        name: "MUNI",
        type: "Travel",
        time: 1695539429000,
      },
      {
        eventType: "TXN_AUTHED",
        eventTime: 4,
        txnId: "t3",
        amount: 90,
        name: "Chevron",
        type: "Gas",
        time: 1695712229000,
      },
    ],
  },
];

export default sampleTransactions;
